add basic logs in the predeployment job

diff --git a/servarr/templates/pre-deployment-job.yaml b/servarr/templates/pre-deployment-job.yaml
--- a/servarr/templates/pre-deployment-job.yaml
+++ b/servarr/templates/pre-deployment-job.yaml
@@ -25,11 +25,33 @@ spec:
           - "sh"
           - "-c"
           - |
+            echo "-- DEBUG: qBitTorrent config file being used"
             cat /tmp/qBittorrent.conf
-            mkdir -p /mnt/qBittorrent/config/
-            cp -p /tmp/qBittorrent.conf /mnt/qBittorrent/config/qBittorrent.conf
-            chown -R 568:568 /mnt/
-            chmod 0644 /mnt/qBittorrent/config/qBittorrent.conf
+            if mkdir -p /mnt/qBittorrent/config/ ; then
+              echo "-- INFO: Created qBitTorrent config directory"
+            else
+              echo "-- ERROR: An error occurred during the creation of the following path: /mnt/qBittorrent/config/"
+              exit 1
+            fi
+            if cp -p /tmp/qBittorrent.conf /mnt/qBittorrent/config/qBittorrent.conf ; then
+              echo "-- INFO: qBitTorrent config file moved in its config directory"
+            else
+              echo "-- ERROR: An error occurred during the qBitTorrent config copy to /mnt/qBittorrent/config/qBittorrent.conf"
+              exit 1
+            fi
+            if chown -R 568:568 /mnt/ ; then
+              echo "-- INFO: /mnt owner changed!"
+            else
+              echo "-- ERROR: An error occurred during the /mnt owner change"
+              exit 1
+            fi
+            if chmod 0644 /mnt/qBittorrent/config/qBittorrent.conf ; then
+              echo "-- INFO: qBitTorrent config file permissions changed!"
+            else
+              echo "-- ERROR: An error occurred while changing the qBitTorrent config file permissions"
+              exit 1
+            fi
+            echo "-- DEBUG: /mnt/qBitTorrent/config/ directory content"
             ls -la /mnt/qBittorrent/config/
           volumeMounts:
             - name: torrent-config-volume
